# action.yml
name: "Discord - Dispatch Deploy"
author: "A Few Dragons"
description: "Deploy an application to Discord using Discord Dispatch"
branding:
  icon: "upload"
  color: "purple"
inputs:
  applicationId:
    description: "Discord Application/Client id"
    required: true
  branchName:
    description: "Discord branch id"
    required: true
  botToken:
    description: "Discord bot token"
    required: true
  configPath:
    description: "Discord config path"
    required: true
  buildPath:
    description: "Path of build for application"
    required: true
  drmWrap:
    description: "Apply Discord DRM to the application"
    default: false
    required: false
  executableName:
    description: "Application executable name"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    ApplicationId: ${{ inputs.applicationId }}
    BranchName: ${{ inputs.branchName }}
    BotToken: ${{ inputs.botToken }}
    ConfigPath: ${{ inputs.configPath }}
    BuildPath: ${{ inputs.buildPath }}
    DrmWrap: ${{ inputs.drmWrap }}
    ExecutableName: ${{ inputs.executableName }}
